language: node_js
node_js:
- node
script:
- node update-package-version.js
- npm run build
- npm pack
deploy:
  provider: releases
  api_key:
    secure: github-deploy-key
  file_glob: true
  file: hitbox-*.tgz
  skip_cleanup: true
  on:
    tags: true
