language: node_js
node_js:
  - "node"
script:
  - node update-package-version.js
  - npm run build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: hitbox-*.tgz
  skip_cleanup: true
  on:
    tags: true